### ISSUE TITLE
Dynamically change the physical parameters in setup()

### ISSUE THREAD

**Issue by Logenleedev** [dennisppaul/teilchen#6]
I want to dynamically adjust parameters like mGravity.force().y and the length of the pendulum. Seems like right now, once we define such parameters in setup(), it cannot be changed. Any adjustment will lead to the failure of the simulation. Just wondering is this the limitation of teilchen?

**Comment by Logenleedev** [comment]
Hi Dennis. Thanks for the quick reply. Let's say I want to dynamically change the gravity of the visualization in the [Gravity Example](https://github.com/dennisppaul/teilchen/blob/master/processing-library/teilchen/examples/Lesson01_Gravity/Lesson01_Gravity.pde). I added this line at the end of the draw() so that under certain condition, the gravity will change.


```
if (some condition) {
  Gravity mGravity = new Gravity();
  mGravity.force().set(10, -50);
  mPhysics.add(mGravity);
}
```

The issue is since draw() will be called an infinite amount of time, it seems like we keep adding gravity into the system which makes the whole simulation unrealistic. My question is: is there a way to reset/erase the previous gravity and add the new gravity?

**Comment by dennisppaul** [comment]
ok, i see what the problem is. the misunderstanding is in how you are using the gravity object. in your code example you are  instantiating a gravity object and add it to the simulation every time *some condition* is true. however, all previously added gravity object remain in the simulation. therefore you will end up with an ever growing number of gravitiy objects.

what i assume you want is to just have a singel gravity object of which you only manipulate the force every time a condition is true. i therefore suggest you write your code something like this:

```
/* declare gravity *globally* ONCE */
Gravity mGravity;
boolean some_condition;

void setup() {
    /* instantiate gravity and add it to the simulation ONCE */
    mGravity = new Gravity();
    mPhysics.add(mGravity);
    // ...
}

void draw() {
    /* if condition is true change the force of gravity */
    if (some_condition) {
        mGravity.force().set(0, 50);
    }
    // ...
}

```

**Comment by Logenleedev** [comment]
Thanks Dennis! It perfectly solves my problem. I will close this thread now.
